services:
  back-express:
    build:
      context: .
      dockerfile: Dockerfile.back-express
    ports:
      - "3000:3000"
    networks:
      - app-network
    working_dir: /app
    develop:
      watch:
        - action: sync
          path: ./packages/back-express
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: ./packages/back-express/package.json

  front-react:
    build:
      context: .
      dockerfile: Dockerfile.front-react
    ports: 
      - "5173:5173"
    working_dir: /app
    develop:
      watch:
        - action: rebuild
          path: ./packages/front-react/package.json
        - action: sync
          path: ./packages/front-react
          target: /app
          ignore:
            - node_modules/

  database:
    image: paradedb/paradedb:latest
    container_name: database
    networks:
      - app-network
    environment:
      POSTGRES_USER: "pablo_escobar_gaviria"
      POSTGRES_PASSWORD: "APyRnWxbJu7JB#"
      POSTGRES_DB: "narcos"
    ports:
      - "5433:5432"
    volumes:
      - photo-db:/var/lib/postgresql/data  # Mount the volume for the database data

volumes:
  photo-db:   
    external: true
networks:
  app-network:
    driver: bridge
