services:
  back-express:
    build:
      context: .
      dockerfile: Dockerfile.back-express
    ports: 
      - "3000:3000"
    working_dir: /app
    develop:
      watch:
        - action: sync
          path: ./packages/back-express
          target: /app/
          ignore:
            - node_modules/
        - action: rebuild
          path: ./packages/back-express/package.json

  front-react:
    build:
      context: .
      dockerfile: Dockerfile.front-react
    ports: 
      - "5173:5173"
    working_dir: /app
    develop:
      watch:
        - action: rebuild
          path: ./packages/front-react/package.json
        - action: sync
          path: ./packages/front-react
          target: /app
          ignore:
            - node_modules/
