services:
  back-express:
    build:
      context: .
      dockerfile: Dockerfile.back-express
    ports: 
      - "3000:3000"
    working_dir: /app
    develop:
      watch:
        - action: sync
          path: ./packages/back-express
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
